// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.23.3
// source: plumber/plumber.proto

package plumber

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageType int32

const (
	StorageType_STORAGE_UNSPECIFIED StorageType = 0
	StorageType_STORAGE_LFS         StorageType = 1
	StorageType_STORAGE_HTTP        StorageType = 2
	StorageType_STORAGE_S3          StorageType = 3
	StorageType_STORAGE_GCS         StorageType = 4
	StorageType_STORAGE_GIT         StorageType = 5
)

// Enum value maps for StorageType.
var (
	StorageType_name = map[int32]string{
		0: "STORAGE_UNSPECIFIED",
		1: "STORAGE_LFS",
		2: "STORAGE_HTTP",
		3: "STORAGE_S3",
		4: "STORAGE_GCS",
		5: "STORAGE_GIT",
	}
	StorageType_value = map[string]int32{
		"STORAGE_UNSPECIFIED": 0,
		"STORAGE_LFS":         1,
		"STORAGE_HTTP":        2,
		"STORAGE_S3":          3,
		"STORAGE_GCS":         4,
		"STORAGE_GIT":         5,
	}
)

func (x StorageType) Enum() *StorageType {
	p := new(StorageType)
	*p = x
	return p
}

func (x StorageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StorageType) Descriptor() protoreflect.EnumDescriptor {
	return file_plumber_plumber_proto_enumTypes[0].Descriptor()
}

func (StorageType) Type() protoreflect.EnumType {
	return &file_plumber_plumber_proto_enumTypes[0]
}

func (x StorageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StorageType.Descriptor instead.
func (StorageType) EnumDescriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{0}
}

type OperationType int32

const (
	OperationType_OPERATION_UNSPECIFIED OperationType = 0
	OperationType_OPERATION_ACID        OperationType = 1
	OperationType_OPERATION_DOOBIE      OperationType = 2
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_UNSPECIFIED",
		1: "OPERATION_ACID",
		2: "OPERATION_DOOBIE",
	}
	OperationType_value = map[string]int32{
		"OPERATION_UNSPECIFIED": 0,
		"OPERATION_ACID":        1,
		"OPERATION_DOOBIE":      2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_plumber_plumber_proto_enumTypes[1].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_plumber_plumber_proto_enumTypes[1]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{1}
}

type MediaIn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input     []*Media   `protobuf:"bytes,1,rep,name=input,proto3" json:"input,omitempty"`
	Operation *Operation `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Callerid  *CallerID  `protobuf:"bytes,3,opt,name=callerid,proto3" json:"callerid,omitempty"`
}

func (x *MediaIn) Reset() {
	*x = MediaIn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plumber_plumber_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MediaIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaIn) ProtoMessage() {}

func (x *MediaIn) ProtoReflect() protoreflect.Message {
	mi := &file_plumber_plumber_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaIn.ProtoReflect.Descriptor instead.
func (*MediaIn) Descriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{0}
}

func (x *MediaIn) GetInput() []*Media {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *MediaIn) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *MediaIn) GetCallerid() *CallerID {
	if x != nil {
		return x.Callerid
	}
	return nil
}

type CallerID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *CallerID) Reset() {
	*x = CallerID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plumber_plumber_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CallerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallerID) ProtoMessage() {}

func (x *CallerID) ProtoReflect() protoreflect.Message {
	mi := &file_plumber_plumber_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallerID.ProtoReflect.Descriptor instead.
func (*CallerID) Descriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{1}
}

func (x *CallerID) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type MuxfarmID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mid string `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
}

func (x *MuxfarmID) Reset() {
	*x = MuxfarmID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plumber_plumber_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MuxfarmID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuxfarmID) ProtoMessage() {}

func (x *MuxfarmID) ProtoReflect() protoreflect.Message {
	mi := &file_plumber_plumber_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuxfarmID.ProtoReflect.Descriptor instead.
func (*MuxfarmID) Descriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{2}
}

func (x *MuxfarmID) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

type MuxfarmObject struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Muxfarmid *MuxfarmID `protobuf:"bytes,1,opt,name=muxfarmid,proto3" json:"muxfarmid,omitempty"`
	Mediain   *MediaIn   `protobuf:"bytes,2,opt,name=mediain,proto3" json:"mediain,omitempty"`
}

func (x *MuxfarmObject) Reset() {
	*x = MuxfarmObject{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plumber_plumber_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MuxfarmObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MuxfarmObject) ProtoMessage() {}

func (x *MuxfarmObject) ProtoReflect() protoreflect.Message {
	mi := &file_plumber_plumber_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MuxfarmObject.ProtoReflect.Descriptor instead.
func (*MuxfarmObject) Descriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{3}
}

func (x *MuxfarmObject) GetMuxfarmid() *MuxfarmID {
	if x != nil {
		return x.Muxfarmid
	}
	return nil
}

func (x *MuxfarmObject) GetMediain() *MediaIn {
	if x != nil {
		return x.Mediain
	}
	return nil
}

type Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Storagetype StorageType `protobuf:"varint,1,opt,name=storagetype,proto3,enum=plumber.plumber.StorageType" json:"storagetype,omitempty"`
	Uri         string      `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
}

func (x *Media) Reset() {
	*x = Media{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plumber_plumber_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_plumber_plumber_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{4}
}

func (x *Media) GetStoragetype() StorageType {
	if x != nil {
		return x.Storagetype
	}
	return StorageType_STORAGE_UNSPECIFIED
}

func (x *Media) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Acid   *Acid   `protobuf:"bytes,1,opt,name=acid,proto3" json:"acid,omitempty"`
	Doobie *Doobie `protobuf:"bytes,2,opt,name=doobie,proto3" json:"doobie,omitempty"`
}

func (x *Operation) Reset() {
	*x = Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plumber_plumber_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_plumber_plumber_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{5}
}

func (x *Operation) GetAcid() *Acid {
	if x != nil {
		return x.Acid
	}
	return nil
}

func (x *Operation) GetDoobie() *Doobie {
	if x != nil {
		return x.Doobie
	}
	return nil
}

type Revelio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Media *Media `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
}

func (x *Revelio) Reset() {
	*x = Revelio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plumber_plumber_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Revelio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Revelio) ProtoMessage() {}

func (x *Revelio) ProtoReflect() protoreflect.Message {
	mi := &file_plumber_plumber_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Revelio.ProtoReflect.Descriptor instead.
func (*Revelio) Descriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{6}
}

func (x *Revelio) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type Acid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Media *Media `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
}

func (x *Acid) Reset() {
	*x = Acid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plumber_plumber_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Acid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Acid) ProtoMessage() {}

func (x *Acid) ProtoReflect() protoreflect.Message {
	mi := &file_plumber_plumber_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Acid.ProtoReflect.Descriptor instead.
func (*Acid) Descriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{7}
}

func (x *Acid) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type Doobie struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Media *Media `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
}

func (x *Doobie) Reset() {
	*x = Doobie{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plumber_plumber_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doobie) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doobie) ProtoMessage() {}

func (x *Doobie) ProtoReflect() protoreflect.Message {
	mi := &file_plumber_plumber_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doobie.ProtoReflect.Descriptor instead.
func (*Doobie) Descriptor() ([]byte, []int) {
	return file_plumber_plumber_proto_rawDescGZIP(), []int{8}
}

func (x *Doobie) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

var File_plumber_plumber_proto protoreflect.FileDescriptor

var file_plumber_plumber_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2f, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0xa8, 0x01, 0x0a, 0x07, 0x4d, 0x65, 0x64,
	0x69, 0x61, 0x49, 0x6e, 0x12, 0x2c, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x05, 0x69, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x38, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x35, 0x0a, 0x08,
	0x63, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x2e, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x44, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x65,
	0x72, 0x69, 0x64, 0x22, 0x1c, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69,
	0x64, 0x22, 0x1d, 0x0a, 0x09, 0x4d, 0x75, 0x78, 0x66, 0x61, 0x72, 0x6d, 0x49, 0x44, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x64,
	0x22, 0x7d, 0x0a, 0x0d, 0x4d, 0x75, 0x78, 0x66, 0x61, 0x72, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x12, 0x38, 0x0a, 0x09, 0x6d, 0x75, 0x78, 0x66, 0x61, 0x72, 0x6d, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70,
	0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x75, 0x78, 0x66, 0x61, 0x72, 0x6d, 0x49, 0x44,
	0x52, 0x09, 0x6d, 0x75, 0x78, 0x66, 0x61, 0x72, 0x6d, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x6d,
	0x65, 0x64, 0x69, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70,
	0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d,
	0x65, 0x64, 0x69, 0x61, 0x49, 0x6e, 0x52, 0x07, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x69, 0x6e, 0x22,
	0x59, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x3e, 0x0a, 0x0b, 0x73, 0x74, 0x6f, 0x72,
	0x61, 0x67, 0x65, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e,
	0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x69, 0x22, 0x67, 0x0a, 0x09, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x61, 0x63, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x41, 0x63, 0x69, 0x64, 0x52, 0x04, 0x61, 0x63,
	0x69, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x64, 0x6f, 0x6f, 0x62, 0x69, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x44, 0x6f, 0x6f, 0x62, 0x69, 0x65, 0x52, 0x06, 0x64, 0x6f, 0x6f,
	0x62, 0x69, 0x65, 0x22, 0x37, 0x0a, 0x07, 0x52, 0x65, 0x76, 0x65, 0x6c, 0x69, 0x6f, 0x12, 0x2c,
	0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x22, 0x34, 0x0a, 0x04,
	0x41, 0x63, 0x69, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x52, 0x05, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x22, 0x36, 0x0a, 0x06, 0x44, 0x6f, 0x6f, 0x62, 0x69, 0x65, 0x12, 0x2c, 0x0a, 0x05,
	0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x6c,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x65,
	0x64, 0x69, 0x61, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x2a, 0x7b, 0x0a, 0x0b, 0x53, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x4f,
	0x52, 0x41, 0x47, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x4c, 0x46,
	0x53, 0x10, 0x01, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45, 0x5f, 0x48,
	0x54, 0x54, 0x50, 0x10, 0x02, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45,
	0x5f, 0x53, 0x33, 0x10, 0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47, 0x45,
	0x5f, 0x47, 0x43, 0x53, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x4f, 0x52, 0x41, 0x47,
	0x45, 0x5f, 0x47, 0x49, 0x54, 0x10, 0x05, 0x2a, 0x54, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x4f, 0x50, 0x45, 0x52,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x41, 0x43, 0x49, 0x44, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4f, 0x50, 0x45, 0x52, 0x41,
	0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x44, 0x4f, 0x4f, 0x42, 0x49, 0x45, 0x10, 0x02, 0x32, 0x91, 0x01,
	0x0a, 0x04, 0x4d, 0x6f, 0x70, 0x73, 0x12, 0x40, 0x0a, 0x06, 0x49, 0x6e, 0x67, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x49, 0x6e, 0x1a, 0x1a, 0x2e, 0x70, 0x6c, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x4d, 0x75, 0x78,
	0x66, 0x61, 0x72, 0x6d, 0x49, 0x44, 0x22, 0x00, 0x12, 0x47, 0x0a, 0x05, 0x50, 0x75, 0x6c, 0x73,
	0x65, 0x12, 0x1a, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x2e, 0x4d, 0x75, 0x78, 0x66, 0x61, 0x72, 0x6d, 0x49, 0x44, 0x1a, 0x1e, 0x2e,
	0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x2e,
	0x4d, 0x75, 0x78, 0x66, 0x61, 0x72, 0x6d, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x00, 0x30,
	0x01, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x73, 0x68, 0x61, 0x63, 0x6b, 0x2f, 0x6d, 0x75, 0x78, 0x66,
	0x61, 0x72, 0x6d, 0x2f, 0x70, 0x6c, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_plumber_plumber_proto_rawDescOnce sync.Once
	file_plumber_plumber_proto_rawDescData = file_plumber_plumber_proto_rawDesc
)

func file_plumber_plumber_proto_rawDescGZIP() []byte {
	file_plumber_plumber_proto_rawDescOnce.Do(func() {
		file_plumber_plumber_proto_rawDescData = protoimpl.X.CompressGZIP(file_plumber_plumber_proto_rawDescData)
	})
	return file_plumber_plumber_proto_rawDescData
}

var file_plumber_plumber_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_plumber_plumber_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_plumber_plumber_proto_goTypes = []interface{}{
	(StorageType)(0),      // 0: plumber.plumber.StorageType
	(OperationType)(0),    // 1: plumber.plumber.OperationType
	(*MediaIn)(nil),       // 2: plumber.plumber.MediaIn
	(*CallerID)(nil),      // 3: plumber.plumber.CallerID
	(*MuxfarmID)(nil),     // 4: plumber.plumber.MuxfarmID
	(*MuxfarmObject)(nil), // 5: plumber.plumber.MuxfarmObject
	(*Media)(nil),         // 6: plumber.plumber.Media
	(*Operation)(nil),     // 7: plumber.plumber.Operation
	(*Revelio)(nil),       // 8: plumber.plumber.Revelio
	(*Acid)(nil),          // 9: plumber.plumber.Acid
	(*Doobie)(nil),        // 10: plumber.plumber.Doobie
}
var file_plumber_plumber_proto_depIdxs = []int32{
	6,  // 0: plumber.plumber.MediaIn.input:type_name -> plumber.plumber.Media
	7,  // 1: plumber.plumber.MediaIn.operation:type_name -> plumber.plumber.Operation
	3,  // 2: plumber.plumber.MediaIn.callerid:type_name -> plumber.plumber.CallerID
	4,  // 3: plumber.plumber.MuxfarmObject.muxfarmid:type_name -> plumber.plumber.MuxfarmID
	2,  // 4: plumber.plumber.MuxfarmObject.mediain:type_name -> plumber.plumber.MediaIn
	0,  // 5: plumber.plumber.Media.storagetype:type_name -> plumber.plumber.StorageType
	9,  // 6: plumber.plumber.Operation.acid:type_name -> plumber.plumber.Acid
	10, // 7: plumber.plumber.Operation.doobie:type_name -> plumber.plumber.Doobie
	6,  // 8: plumber.plumber.Revelio.media:type_name -> plumber.plumber.Media
	6,  // 9: plumber.plumber.Acid.media:type_name -> plumber.plumber.Media
	6,  // 10: plumber.plumber.Doobie.media:type_name -> plumber.plumber.Media
	2,  // 11: plumber.plumber.Mops.Ingest:input_type -> plumber.plumber.MediaIn
	4,  // 12: plumber.plumber.Mops.Pulse:input_type -> plumber.plumber.MuxfarmID
	4,  // 13: plumber.plumber.Mops.Ingest:output_type -> plumber.plumber.MuxfarmID
	5,  // 14: plumber.plumber.Mops.Pulse:output_type -> plumber.plumber.MuxfarmObject
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_plumber_plumber_proto_init() }
func file_plumber_plumber_proto_init() {
	if File_plumber_plumber_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plumber_plumber_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MediaIn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plumber_plumber_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CallerID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plumber_plumber_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MuxfarmID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plumber_plumber_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MuxfarmObject); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plumber_plumber_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Media); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plumber_plumber_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plumber_plumber_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Revelio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plumber_plumber_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Acid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plumber_plumber_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doobie); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plumber_plumber_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plumber_plumber_proto_goTypes,
		DependencyIndexes: file_plumber_plumber_proto_depIdxs,
		EnumInfos:         file_plumber_plumber_proto_enumTypes,
		MessageInfos:      file_plumber_plumber_proto_msgTypes,
	}.Build()
	File_plumber_plumber_proto = out.File
	file_plumber_plumber_proto_rawDesc = nil
	file_plumber_plumber_proto_goTypes = nil
	file_plumber_plumber_proto_depIdxs = nil
}
